# Pre-commit hooks for Relay Server
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: local
    hooks:
      - id: relay-tests
        name: Run Relay Test Suite
        entry: make test
        language: system
        files: '^server/.*\.go$'
        pass_filenames: false
        
      - id: go-fmt
        name: Go Format
        entry: bash -c 'cd server && go fmt ./...'
        language: system
        files: '^server/.*\.go$'
        pass_filenames: false
        
      - id: go-vet
        name: Go Vet
        entry: bash -c 'cd server && go vet ./...'
        language: system
        files: '^server/.*\.go$'
        pass_filenames: false
        
      - id: go-build
        name: Go Build
        entry: bash -c 'cd server && go build -o relay'
        language: system
        files: '^server/.*\.go$'
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict