version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: relay-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: relay_dev
      POSTGRES_USER: relay_user
      POSTGRES_PASSWORD: relay_dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - relay-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U relay_user -d relay_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_dev_data:
    driver: local

networks:
  relay-network:
    driver: bridge