version: '3.8'

services:
  relay-voice:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - PORT=8080
      - LOG_LEVEL=info
    volumes:
      # Mount project directories (adjust paths as needed)
      - ${HOME}/Code:/root/Code:ro
      - ${HOME}/Projects:/root/Projects:ro
      # Mount git and GitHub CLI configs
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}/.ssh:/root/.ssh:ro
      - ${HOME}/.config/gh:/root/.config/gh:ro
      # Mount relay config
      - ${HOME}/.relay:/root/.relay
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Reverse proxy with SSL
  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - relay-voice

volumes:
  caddy_data:
  caddy_config:
