name: Deploy Voice Server

on:
  push:
    branches: [ main ]
    paths:
      - 'voice-server-js/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      DOCKER_HOST: tcp://10.0.0.35:2375  # Use remote Docker daemon
      DOCKER_COMPOSE_FILE: docker-compose.prod.yml
      VOICE_SERVER_IMAGE: relay-voice-server:latest
      # Backend Secrets
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Voice Server image
        run: |
          cd voice-server-js
          docker build -t ${{ env.VOICE_SERVER_IMAGE }} .

      - name: Stop and remove existing containers
        run: |
          cd voice-server-js
          docker compose --file ${{ env.DOCKER_COMPOSE_FILE }} down || true

      - name: Start new container
        run: |
          cd voice-server-js
          docker compose --file ${{ env.DOCKER_COMPOSE_FILE }} up -d --remove-orphans